import Head from 'next/head'
import { useState , useEffect } from 'react';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Stops from '../components/Stops/Stops.stop';
import GetLocation from "../components/Utils/getLocation"

export default function Home() {

  const [coords, setCoords] = useState("");
  useEffect(() => {
    GetLocation(setCoords);
  }, [coords]);
   
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {coords ? (
        <Stops url={process.env.REACT_APP_SERVER_URL + coords} />
      ) : (
        <>
          <h2>Allow Location to See nearby Stops</h2>
          <h2>Deny if Out of Winnipeg</h2>s
        </>
      )}      
    </div>
  )
}
